name: workflow
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run action reason'
        required: false
        type: string
        default: 'manually test'
  push:
    branches:
      - main
      - dev
      - bug/**
      - fix/**
      - bugfix/**
      - feature/**
      - release/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21.13', '1.22.12', '1.23.11', '1.24.5']
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check Go Version and Install Go Dep
        run: |
          go version
          go mod vendor

      - name: Test
        run: make test && make build
